# framework:
#     messenger:
#         buses:
#             message_bus: 
#                 # Other configurations...
#         routing:
#             'App\Message\UserCreatedEvent': 'App\MessageHandler\NotificationHandler'
